# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/falcon_umts/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/falcon_umts/proprietary/bin/ap_gain.bin:system/bin/ap_gain.bin \
    vendor/motorola/falcon_umts/proprietary/bin/ap_gain_mmul.bin:system/bin/ap_gain_mmul.bin \
    vendor/motorola/falcon_umts/proprietary/bin/batt_health:system/bin/batt_health \
    vendor/motorola/falcon_umts/proprietary/bin/charge_only_mode:system/bin/charge_only_mode \
    vendor/motorola/falcon_umts/proprietary/bin/hardware_revisions.sh:system/bin/hardware_revisions.sh \
    vendor/motorola/falcon_umts/proprietary/bin/imsdatadaemon:system/bin/imsdatadaemon \
    vendor/motorola/falcon_umts/proprietary/bin/imsqmidaemon:system/bin/imsqmidaemon \
    vendor/motorola/falcon_umts/proprietary/bin/ims_rtp_daemon:system/bin/ims_rtp_daemon \
    vendor/motorola/falcon_umts/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/motorola/falcon_umts/proprietary/bin/moto_com.sh:system/bin/moto_com.sh \
    vendor/motorola/falcon_umts/proprietary/bin/mount_ext4.sh:system/bin/mount_ext4.sh \
    vendor/motorola/falcon_umts/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/motorola/falcon_umts/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/motorola/falcon_umts/proprietary/bin/qmi_motext_hook:system/bin/qmi_motext_hook \
    vendor/motorola/falcon_umts/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/motorola/falcon_umts/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/motorola/falcon_umts/proprietary/bin/rild:system/bin/rild \
    vendor/motorola/falcon_umts/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/motorola/falcon_umts/proprietary/lib/hw/camera.msm8226.so:system/lib/hw/camera.msm8226.so \
    vendor/motorola/falcon_umts/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/motorola/falcon_umts/proprietary/lib/hw/sensors.msm8226.so:system/lib/hw/sensors.msm8226.so \
    vendor/motorola/falcon_umts/proprietary/lib/libadropbox.so:system/lib/libadropbox.so \
    vendor/motorola/falcon_umts/proprietary/lib/libbabysit.so:system/lib/libbabysit.so \
    vendor/motorola/falcon_umts/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/motorola/falcon_umts/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/motorola/falcon_umts/proprietary/lib/libloc_core.so:system/lib/libloc_core.so \
    vendor/motorola/falcon_umts/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/motorola/falcon_umts/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/motorola/falcon_umts/proprietary/lib/libmdmcutback.so:system/lib/libmdmcutback.so \
    vendor/motorola/falcon_umts/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/motorola/falcon_umts/proprietary/lib/libmotext_inf.so:system/lib/libmotext_inf.so \
    vendor/motorola/falcon_umts/proprietary/lib/libmot_sensorlistener.so:system/lib/libmot_sensorlistener.so \
    vendor/motorola/falcon_umts/proprietary/lib/libOmxVenc.so:system/lib/libOmxVenc.so \
    vendor/motorola/falcon_umts/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/motorola/falcon_umts/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/lib-dplmedia.so:system/vendor/lib/lib-dplmedia.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/lib-imsdpl.so:system/vendor/lib/lib-imsdpl.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/lib-imsqimf.so:system/vendor/lib/lib-imsqimf.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/lib-imsrcs.so:system/vendor/lib/lib-imsrcs.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/lib-imsSDP.so:system/vendor/lib/lib-imsSDP.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/lib-imsvt.so:system/vendor/lib/lib-imsvt.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/lib-imsxml.so:system/vendor/lib/lib-imsxml.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/lib-rtpcommon.so:system/vendor/lib/lib-rtpcommon.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/lib-rtpcore.so:system/vendor/lib/lib-rtpcore.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/lib-rtpdaemoninterface.so:system/vendor/lib/lib-rtpdaemoninterface.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/lib-rtpsl.so:system/vendor/lib/lib-rtpsl.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/motorola/falcon_umts/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/motorola/falcon_umts/proprietary/bin/mm-qcamera-app:system/bin/mm-qcamera-app \
    vendor/motorola/falcon_umts/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/motorola/falcon_umts/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/motorola/falcon_umts/proprietary/lib/libchromatix_imx135_video_hd.so:system/lib/libchromatix_imx135_video_hd.so \
    vendor/motorola/falcon_umts/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/motorola/falcon_umts/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/motorola/falcon_umts/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/motorola/falcon_umts/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/motorola/falcon_umts/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/motorola/falcon_umts/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/motorola/falcon_umts/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/motorola/falcon_umts/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libc2d2_z180.so:system/vendor/lib/libc2d2_z180.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libc2d30.so:system/vendor/lib/libc2d30.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libllvm-a3xx.so:system/vendor/lib/libllvm-a3xx.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libOpenVG.so:system/vendor/lib/libOpenVG.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/motorola/falcon_umts/proprietary/etc/firmware/synaptics-s2316-13091704-175833-falcon.tdat:system/etc/firmware/synaptics-s2316-13091704-175833-falcon.tdat \
    vendor/motorola/falcon_umts/proprietary/etc/sap.conf:system/etc/sap.conf \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/motorola/falcon_umts/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/motorola/falcon_umts/proprietary/etc/firmware/wlan/prima/WCNSS_cfg.dat:system/etc/firmware/wlan/prima/WCNSS_cfg.dat \
    vendor/motorola/falcon_umts/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini:system/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini \
    vendor/motorola/falcon_umts/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_wlan_factory_nv.bin:system/etc/firmware/wlan/prima/WCNSS_qcom_wlan_factory_nv.bin \
    vendor/motorola/falcon_umts/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin:system/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin \
